name: Deploy to S3 Production 

on: workflow_dispatch

env:
  AWS_REGION: "ap-south-1"
  REACT_APP_BASE_URL: "https://sitegrid.io"
  S3_BUCKET: "prod-sitegrid-cloudfront-sitegrid-web-s3"
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy To production S3
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Use Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: NPM Install
      run: npm install --legacy-peer-deps

    - name: NPM Build
      run: REACT_APP_BASE_URL=$REACT_APP_BASE_URL npm run build --verbose

    - name: Sync files to S3
      run: |
        aws s3 sync build/ s3://$S3_BUCKET --include "*" --exclude "index.html"
        aws s3 sync build/ s3://$S3_BUCKET --exclude "*" --include "index.html" --cache-control max-age=0
        aws s3 sync --delete build/ s3://$S3_BUCKET